apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-test-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hpa-app
  template:
    metadata:
      name: hpa-app
      labels:
        app: hpa-app
    spec:
      containers:
      - image: busybox
        name: hpa-app
        command: ["dd", "if=/dev/zero", "of=/dev/null"] # CPUを100%使うように
        resources:
          requests:
            cpu: 200m
            memory: 10Mi
